//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.BranchOffices = new HashSet<BranchOffices>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string SKU { get; set; }
    
        public virtual ICollection<BranchOffices> BranchOffices { get; set; }
    }
}
